codecov:
  max_report_age: off
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1
    wait_for_ci: yes

# Change how pull request comments look
comment:
  layout: "reach,diff,flags,files,footer"

ignore:
  - "benchmarks/*"
  - "examples/*"
  - "/usr/*"
  - "**/boost/*"
