name: CI

on:
  push:
    branches: [ master ]

jobs:
  posix:
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - { toolset: gcc,   compiler: g++-10,     install: g++-10,   os: ubuntu-22.04, cxxstd: 'c++17' }
          - { toolset: gcc,   compiler: g++-11,     install: g++-11,   os: ubuntu-22.04, cxxstd: 'c++17' }
          - { toolset: gcc,   compiler: g++-11,     install: g++-11,   os: ubuntu-22.04, cxxstd: 'c++20' }
          - { toolset: clang, compiler: clang++-11, install: clang-11, os: ubuntu-22.04, cxxstd: 'c++17' }
          - { toolset: clang, compiler: clang++-11, install: clang-11, os: ubuntu-22.04, cxxstd: 'c++20' }
          - { toolset: clang, compiler: clang++-13, install: clang-13, os: ubuntu-22.04, cxxstd: 'c++17' }
          - { toolset: clang, compiler: clang++-13, install: clang-13, os: ubuntu-22.04, cxxstd: 'c++20' }
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.compiler }}
      CXXFLAGS: -std=${{matrix.cxxstd}} -Wall -Wextra
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Autotools
      run: sudo apt install automake
    - name: Install compiler
      run: sudo apt-get install -y ${{ matrix.install }}
    - name: Install Redis
      run: sudo apt-get install -y redis-server
    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: 1.79.0
    - name: Configure
      run: |
        autoreconf -i
        ./configure --with-boost=${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: Build
      run: make
    - name: Check
      run: make check VERBOSE=1
