name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-type: ['sanity']
        runs-on: [ubuntu-22.04]
        compiler: [g++-11]
        cxx-std: ['c++20']
        optim-level: ['-O0']
    runs-on: ${{ matrix.runs-on }}
    env:
      CXX: ${{ matrix.compiler }}
      CXXFLAGS: -std=${{ matrix.cxx-std }} ${{ matrix.optim-level }} -Wall -Wextra
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Autotools
      run: sudo apt install automake
    - name: Install compiler
      run: sudo apt-get install -y ${{ matrix.compiler }}
    - name: Install Redis
      run: sudo apt-get install -y redis-server
    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: 1.79.0
        platform_version: 22.04
    - name: Configure
      run: |
        autoreconf -i
        ./configure --with-boost=${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: Build
      run: make
    - name: Check
      run: make check VERBOSE=1
