name: CI

on: [push, pull_request]

jobs:
  posix:
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - { toolset: gcc,   compiler: g++-10,     install: g++-10,   os: ubuntu-22.04, cxxstd: 'c++17' }
          - { toolset: gcc,   compiler: g++-11,     install: g++-11,   os: ubuntu-22.04, cxxstd: 'c++17' }
          - { toolset: gcc,   compiler: g++-11,     install: g++-11,   os: ubuntu-22.04, cxxstd: 'c++20' }
          - { toolset: clang, compiler: clang++-11, install: clang-11, os: ubuntu-22.04, cxxstd: 'c++17' }
          - { toolset: clang, compiler: clang++-11, install: clang-11, os: ubuntu-22.04, cxxstd: 'c++20' }
          - { toolset: clang, compiler: clang++-13, install: clang-13, os: ubuntu-22.04, cxxstd: 'c++17' }
          - { toolset: clang, compiler: clang++-13, install: clang-13, os: ubuntu-22.04, cxxstd: 'c++20' }
    runs-on: ${{ matrix.os }}
    env:
      CXXFLAGS: -g -O0 -std=${{matrix.cxxstd}} -Wall -Wextra
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install CMake
      run: sudo apt-get -y install cmake
    - name: Install compiler
      run: sudo apt-get install -y ${{ matrix.install }}
    - name: Install Redis
      run: sudo apt-get install -y redis-server
    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: 1.79.0
        platform_version: 22.04
    - name: Run CMake
      run: |
        BOOST_ROOT=${{steps.install-boost.outputs.BOOST_ROOT}} cmake -DCMAKE_CXX_COMPILER="${{matrix.compiler}}" -DCMAKE_CXX_FLAGS="${{env.CXXFLAGS}}"
    - name: Build
      run: make
    - name: Check
      run: make test VERBOSE=1
