name: Coverage

on:
  push:
    branches:
      - master
jobs:
  posix:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-22.04
    env:
      CXX: g++-11
      CXXFLAGS: -std=c++20 -Wall -Wextra --coverage -fkeep-inline-functions -fkeep-static-functions -O0
      LDFLAGS: --coverage
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Autotools
      run: sudo apt install automake
    - name: Install compiler
      run: sudo apt-get install -y g++-11
    - name: Install Redis
      run: sudo apt-get install -y redis-server
    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: 1.79.0
        platform_version: 22.04
    - name: Configure
      run: |
        autoreconf -i
        ./configure --with-boost=${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: Build
      run: make
    - name: Check
      run: make check VERBOSE=1
        #    - name: Generate coverage report
        #      run: |
        #        lcov --base-directory . --directory tests/ --output-file aedis.info --capture
        #        lcov --remove aedis.info '/usr/*' "${{ steps.install-boost.outputs.BOOST_ROOT }}/include/boost/*" --output-file aedis.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        gcov: true

